### ISSUE TITLE
Allow customization of "None" intent in compare command

### ISSUE THREAD

**Issue by rozele** [microsoft/NLU.DevOps#211]
For some NLU providers like Dialogflow, the "None" intent is handled with a default fallback intent. Currently the `compare` command only detects negative intents with `null` or `"None"` values, but we may want to support other user configured values, like `"Default"`, `"NoMatch"`, etc.

**Comment by saroup** [comment]
@rozele  I am wondering if there is a provider (LUIS, DF or LEX) that actually returns a null value.
At this point I don't think we need a special handling for the None intent. We actually want to treat it as any other intent since utterances should be classified as None (or equivalent) when it doesn't match any intent and the test set should have examples of utterances where the none intent is expected and that would results in a TP.

**Comment by rozele** [comment]
Closing this issue, as we are no longer considering true negatives.

**Comment by rozele** [comment]
Re-opening.
